### PR TITLE
Got rid of useless files :D

### PR DESCRIPTION
**Pull request by FantasyIsBae**
My OCD again .... xD @LegitSoulja

### CODE REVIEW

**Comment by FantasyIsBae** [comment]
I got rid of the files that haven't been used , and just take up space xD

**Comment by LegitSoulja** [comment]
You just wasted time on your life.

**Comment by LegitSoulja** [comment]
Nobody uses this, except people who wants there own client

**Comment by FantasyIsBae** [comment]
I mean it took 2 minutes so not really

**Comment by LegitSoulja** [comment]
This client, and our client is different

**Comment by LegitSoulja** [comment]
And this is a backup

**Comment by FantasyIsBae** [comment]
Yeah i know yours uses more high level s**t xD

**Comment by FantasyIsBae** [comment]
RIP in spaghetti never forghetti

**Comment by LegitSoulja** [comment]
:/ professional I recommend, and there's no R.I.P. You still have the work

**Comment by LegitSoulja** [comment]
Relive it. But this is a backup (original)

**Comment by FantasyIsBae** [comment]
Ok , i will try improving it :)

**Pull request closed without merging**
